name: beauty_client
description: "Beauty Client for Beauty Service"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_bloc: ^8.1.6
  dio: ^5.7.0
  retrofit: ^4.4.2
  flutter_secure_storage: ^9.2.2
  rxdart: ^0.28.0
  auto_route: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.14
  json_serializable:
  freezed: ^2.5.7

flutter:
  uses-material-design: true
