// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcOFXtLXCkBwUuvSU0G_VUboGniaTYGGs',
    appId: '1:679846823395:web:f2366677908098c392ccd6',
    messagingSenderId: '679846823395',
    projectId: 'beauty-client-1c87a',
    authDomain: 'beauty-client-1c87a.firebaseapp.com',
    storageBucket: 'beauty-client-1c87a.firebasestorage.app',
    measurementId: 'G-0V5S8S8FT8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACnYeRZWQm99HWeD6jNuKGrdAlSv7691I',
    appId: '1:679846823395:android:905cf3fc4d8634ac92ccd6',
    messagingSenderId: '679846823395',
    projectId: 'beauty-client-1c87a',
    storageBucket: 'beauty-client-1c87a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbuop12RVSjVCY2uRvisq2aGUUhg0U6Zg',
    appId: '1:679846823395:ios:c12ac6985c73f5ff92ccd6',
    messagingSenderId: '679846823395',
    projectId: 'beauty-client-1c87a',
    storageBucket: 'beauty-client-1c87a.firebasestorage.app',
    iosBundleId: 'com.fedkru.beautyClient',
  );
}
